### ISSUE TITLE
Dependency error in the latest release

### ISSUE THREAD

**Issue by FelixGirard** [iTwin/iTwinUI-layouts#92]
#### Environment

- **Package version(s)**: ^0.4.0
- **Operating System**: Windows
- **Browser name and version**: Chrome

#### Steps to reproduce

1. Try to install the latest version 0.4.0

#### Actual behavior

I get this error: 
`In ..\..: "@itwin/itwinui-layouts-css@workspace:*" is in the dependencies but no package named "@itwin/itwinui-layouts-css" is present in the workspace`

#### Expected behavior

I would expect the installation to succeed.

#### Additional information

I suppose the versions from the pnpm workspace don't get replaced correctly for the release?

**Comment by mayank99** [comment]
Closing as this was fixed by https://github.com/iTwin/iTwinUI-layouts/commit/3bc9e7e40e8e94750c419185beb0e9e1713d095e in [0.4.1](https://github.com/iTwin/iTwinUI-layouts/releases/tag/%40itwin%2Fitwinui-layouts-react%400.4.1).
